---
galaxy_info:
  author: local
  description: Deploy Sonatype Nexus Repository in Docker behind Traefik.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - nexus
    - repository
    - docker

dependencies: []
