---

- name: Setup Nexus Service
  ansible.builtin.import_tasks: installation.yml
  tags:
    - install_nexus
    - setup_nexus

- name: Configuration Nexus | Delete repo
  ansible.builtin.include_tasks: delete-repo.yml
  loop: "{{ delete_repos }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - delete_repository

- name: Configuration Nexus | Create blob store
  ansible.builtin.include_tasks: create-blob-store.yml
  loop: "{{ create_blob_stores }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_blob_store

- name: Configuration Nexus | Create cleanup policy
  ansible.builtin.include_tasks: create-cleanup-policy.yml
  loop: "{{ create_cleanup_policies }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_cleanup_policy

- name: Configuration Nexus | Create APT repo
  ansible.builtin.include_tasks: create-apt-repo.yml
  loop: "{{ create_apt_repository }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_apt_repo

- name: Configuration Nexus | Create Docker repo
  ansible.builtin.include_tasks: create-docker-repo.yml
  loop: "{{ create_docker_repository }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_docker_repo

- name: Configuration Nexus | Create Raw repo
  ansible.builtin.include_tasks: create-raw-repo.yml
  loop: "{{ create_raw_repository }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_raw_repo

- name: Configuration Nexus | Create PyPI repo
  ansible.builtin.include_tasks: create-pypi-repo.yml
  loop: "{{ create_pypi_repository }}"
  loop_control:
    loop_var: item
  tags:
    - setup_nexus
    - config_nexus
    - create_pypi_repo

- name: Configuration Nexus | Enable Anonymous Access
  ansible.builtin.include_tasks: anonymous-config.yml
  tags:
    - setup_nexus
    - config_nexus
    - anonymous_access

- name: Configuration Nexus | Configure Realms
  ansible.builtin.include_tasks: realms-config.yml
  loop: "{{ realms_config }}"
  loop_control:
    loop_var: realm_config
  tags:
    - setup_nexus
    - config_nexus
    - realms_config

- name: Configuration Nexus | Auth Configuration | Create Role and User
  ansible.builtin.include_tasks: auth-config.yml
  tags:
    - setup_nexus
    - config_nexus
    - auth_config
