---
- name: Update and Install packages
  ansible.builtin.include_tasks:
    file: packages.yml
  tags:
    - install_packages

- name:  fail2ban Installation and configuration
  ansible.builtin.include_tasks:
    file: fail2ban.yml
  tags:
    - fail2ban_setup