---

- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
    state: present
  loop:
    - web_net
    - app_net
  tags:
    - preparing
    - docker

- name: Create service directory
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
    mode: "0755"
  tags:
    - preparing

- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ service_dir }}/docker-compose.yml"
    mode: "0644"
  notify: Restart Portainer
  tags:
    - preparing

- name: Template environment file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_dir }}/.env"
    mode: "0600"
  notify: Restart Portainer
  tags:
    - preparing

- name: Pull Docker images
  community.docker.docker_compose_v2_pull:
    project_src: "{{ service_dir }}"
  register: compose_pull
  tags:
    - pull

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir }}"
  register: compose_deploy
  tags:
    - deploy
