---

# Docker image version for Nexus
nexus_image_tag: "3.94.1"

# Container restart policy (always, on-failure, unless-stopped)
restart_policy: "always"

# Service directory on the remote host
service_dir: "{{ project_dir }}/nexus"

# Domain names
nexus_main_domain: "repo.{{ main_domain }}"
nexus_hub_domain: "hub.{{ main_domain }}"

# List of repositories to delete
delete_repos:
  - maven-snapshots
  - maven-public
  - maven-central
  - maven-releases
  - nuget-hosted
  - nuget-group
  - nuget.org-proxy


# List of blob stores to create
create_blob_stores:
  - apt
  - docker
  - raw

# List of APT proxy repositories to create

create_apt_proxy_repos:
  - name: ubuntu-proxy
    remote_url: "http://archive.ubuntu.com/ubuntu/"
    distribution: "jammy"
    blob_store: "apt"
  # - name: debian-proxy
  #   remote_url: "http://deb.debian.org/debian/"
  #   distribution: "bookworm"
  #   blob_store: "apt"
