---
- name: Prune unused Docker resources
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    builder_cache: true
  tags:
    - docker_cleanup