---

- name: Setup GitLab Service | Installation
  ansible.builtin.import_tasks: installation.yml
  tags:
    - install_gitlab
    - setup_gitlab

- name: Configuration GitLab | Configure Runners
  ansible.builtin.include_tasks: configure-runner.yml
  loop: "{{ gitlab_runners }}"
  loop_control:
    loop_var: item
  when: gitlab_runners is defined and gitlab_runners
  tags:
    - setup_gitlab
    - config_gitlab
    - configure_runner
