---

- name: Setup Hermes WebUI Service | Preflight
  ansible.builtin.import_tasks: preflight.yml
  tags:
    - install_hermes_webui
    - setup_hermes_webui
    - hermes_webui_preflight
    - preparing

- name: Setup Hermes WebUI Service | Deploy
  ansible.builtin.import_tasks: deploy.yml
  tags:
    - install_hermes_webui
    - setup_hermes_webui
    - hermes_webui_deploy
    - deploy

- name: Setup Hermes WebUI Service | Verify
  ansible.builtin.import_tasks: verify.yml
  tags:
    - install_hermes_webui
    - setup_hermes_webui
    - hermes_webui_verify
    - verify
