---

- name: Setup Hermes WebUI Service | Preflight
  ansible.builtin.import_tasks: preflight.yml
  tags:
    - always

- name: Setup Hermes WebUI Service | Installation
  ansible.builtin.import_tasks: installation.yml
  tags:
    - install_hermes_webui
    - setup_hermes_webui

- name: Setup Hermes WebUI Service | Verification
  ansible.builtin.import_tasks: verify.yml
  tags:
    - install_hermes_webui
    - setup_hermes_webui
    - verify
