---
# Default variables for Traefik setup

#traefik image tag
traefik_image_tag: "v3.7.10"

#traefik sub domain 
traefik_domain: "traefik.{{ main_domain }}"

#traefik restart policy
restart_policy: "on-failure"

#traefik email for acme challenge
acme_email: hossein3piol@proton.me

#traefik service directory
service_dir: "{{ project_dir }}/traefik"


