---

- name: Create a docker network with name
  docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
  loop:
    - web_net
    - app_net
  tags:
    - traefik_preparing
    - docker

- name: Creates directory
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - traefik_preparing

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ service_dir }}/compose.yml"
  tags:
    - traefik_preparing

- name: Template a file to path
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_dir }}/.env"
  tags:
    - traefik_preparing

- name: Pull images for project
  community.docker.docker_compose_v2_pull:
    project_src: "{{ service_dir }}"
  tags:
    - pull

- name: deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir }}"
  tags:
    - deploy