---

- name: docker preparing
  ansible.builtin.import_tasks: preparing.yml
  tags:
    - docker_preparing
    - docker

- name: docker installation
  ansible.builtin.import_tasks: installation.yml
  tags: 
    - docker_installation
    - docker

- name: docker configuration
  ansible.builtin.import_tasks: configuration.yml
  tags: 
    - docker_configuration
    - docker

