---
all:
  children:
    ecorp:
      children:
        ir-ecorp:
          hosts:
            iran-nexus:
              ansible_host: 185.239.2.95
              ansible_user: root
              ansible_port: 3031
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              # ansible_ssh_common_args: >-
              #   -o IdentitiesOnly=yes
              #   -o ProxyCommand="nc -x 127.0.0.1:10900 -X 5 %h %p"
              ansible_ssh_common_args: >-
                -o ProxyJump=iranserver-okex
                -o IdentitiesOnly=yes
              # ansible_python_interpreter: /usr/bin/python3
            iran-sepiol:
              ansible_host: 2.144.25.102
              ansible_user: root
              ansible_port: 22
              ansible_ssh_private_key_file: ~/.ssh/id_rsa

        eu-ecorp:
          hosts:
            stockholm:
              ansible_host: 77.221.141.93
              ansible_user: root
              ansible_port: 3031
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
            hetzner-cactus:
              ansible_host: 89.167.72.70
              ansible_user: root
              ansible_port: 3031
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
