---
all:
  children:
    amatisdadeh:
      children:
        ovh_vms:
          hosts:
            mizito:
              ansible_host: 91.121.60.75
              ansible_user: root
              ansible_port: 2223
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              
    nexus:
      hosts:
        nexus-01:
          ansible_host: 185.239.2.95
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          # ansible_ssh_common_args: >-
          #   -o IdentitiesOnly=yes
          #   -o ProxyCommand="nc -x 127.0.0.1:10900 -X 5 %h %p"
          # ansible_python_interpreter: /usr/bin/python3