---
all:
  children:
    amatisdadeh:
      children:
        mail_servers:
          hosts:
            mail-01:
              ansible_host: 192.168.56.111

        web_servers:
          hosts:
            web-01:
              ansible_host: 192.168.56.112

    nexus:
      hosts:
        nexus-01:
          ansible_host: 185.239.2.95
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
          ansible_ssh_common_args: >-
            -o IdentitiesOnly=yes
            -o ProxyCommand="nc -x 127.0.0.1:10900 -X 5 %h %p"
          ansible_python_interpreter: /usr/bin/python3